/**
 * Created by Benja on 5/28/2017.
 */
import {SecurityUser} from "../security/User";
import {CreditorGroup} from "./Group";
import {CreditorClassification} from "./Classification";
import {AdminBranch} from "../admin/Branch";
import {AdminCountry} from "../admin/Country";
import {SystemTitle} from "../system/Title";
import {SystemPaymentTerm} from "../system/PaymentTerm";
import {CreditorParameter} from "./Parameter";
import {AdminCityTown} from "../admin/CityTown";
import {AdminProvince} from "../admin/Province";
import {SystemSettleDiscMethod} from "../system/SettleDiscMethod";
import {SystemTradeLevel} from "../system/TradeLevel";
import {SystemBEEType} from "../system/BEEType";
import {SystemBEELevel} from "../system/BEELevel";

export class Creditor {
  public id: number;
  public accNo: string;
  public tradeName: string;
  public regName: string;
  public parent: Creditor;
  public regNo: string;
  public vatVendor: boolean;
  public vatNo: string;
  public telNo: string;
  public faxNo: string;
  public webSite: string;
  public street1: string;
  public street2: string;
  public street3: string;
  public street4: string;
  public streetPostalCode: string;
  public box1: string;
  public box2: string;
  public box3: string;
  public box4: string;
  public boxPostalCode: string;
  public group: CreditorGroup;
  public classification: CreditorClassification;
  public branch: AdminBranch;
  public country: AdminCountry;
  public province: AdminProvince;
  public city: AdminCityTown;
  public accSName: string;
  public accFName: string;
  public accTitle: SystemTitle;
  public accCellNo: string;
  public accEmail: string;
  public oppSName: string;
  public oppFName: string;
  public oppTitle: SystemTitle;
  public oppCellNo: string;
  public oppEmail: string;
  public bankName: string;
  public bankBranchNo: string;
  public bankAccNo: string;
  public bankAccName: string;
  public payTerm: SystemPaymentTerm;
  public settleDiscount: number;
  public settleDays: number;
  public settleDiscMethod: SystemSettleDiscMethod;
  public tradeDiscount: number;
  public tradeLevel: SystemTradeLevel;
  public beeType: SystemBEEType;
  public beeScore: number;
  public beeLevel: SystemBEELevel;
  public beeCertReceived: boolean;
  public beeCertExpDate: Date;
  public beeOwnership: number;
  public beeWoman: number;
  public beeYouth: number;
  public empDisabled: number;
  public orderReq: boolean;
  public suspended: boolean;
  public suspendedDate: Date;
  public createDate: Date;
  public createUser: SecurityUser;
  public parameters: CreditorParameter;


  constructor() {
    this.accNo = "";
    this.tradeName = "";
    this.regName = "";
    this.regNo = "";
    this.vatVendor = false;
    this.vatNo = "";
    this.telNo = "";
    this.faxNo = "";
    this.webSite = "";
    this.street1 = "";
    this.street2 = "";
    this.street3 = "";
    this.street4 = "";
    this.streetPostalCode = "";
    this.box1 = "";
    this.box2 = "";
    this.box3 = "";
    this.box4 = "";
    this.boxPostalCode = "";
    this.accSName = "";
    this.accFName = "";
    this.accCellNo = "";
    this.accEmail = "";
    this.oppSName = "";
    this.oppFName = "";
    this.oppCellNo = "";
    this.oppEmail = "";
    this.bankName = "";
    this.bankBranchNo = "";
    this.bankAccNo = "";
    this.bankAccName = "";
    this.settleDiscount = 0;
    this.settleDays = 0;
    this.tradeDiscount = 0;
    this.beeScore = 0;
    this.beeCertReceived = false;
    this.beeCertExpDate = null;
    this.beeOwnership = 0;
    this.beeWoman = 0;
    this.beeYouth = 0;
    this.empDisabled = 0;
    this.orderReq = false;
    this.suspended = false;
    this.createDate = new Date();
  }
}
